#####
###   Configurations for calculating LAGGED PROJECTIONS in 2022
#####

READING_2022.config <- list(
     READING.2022 = list(
                 sgp.content.areas=c("READING", "READING"),
                 sgp.baseline.content.areas=c("READING", "READING"),
                 sgp.panel.years=c("2019", "2022"),
                 sgp.baseline.panel.years=c("2019", "2022"),
                 sgp.grade.sequences=list(c("0", "3")),
                 sgp.baseline.grade.sequences=list(c("0", "3")),
                 sgp.projection.sequence="READING_GRADE_3"),
     READING.2022 = list(
                 sgp.content.areas=c("READING", "READING", "READING"),
                 sgp.baseline.content.areas=c("READING", "READING", "READING"),
                 sgp.baseline.panel.years=c("2018", "2019", "2022"),
                 sgp.panel.years=c("2018", "2019", "2022"),
                 sgp.grade.sequences=list(c("0", "1", "4")),
                 sgp.baseline.grade.sequences=list(c("0", "1", "4")),
                 sgp.projection.sequence="READING_GRADE_4"),
     READING.2022 = list(
                 sgp.content.areas=c("READING", "READING", "READING"),
                 sgp.baseline.content.areas=c("READING", "READING", "READING"),
                 sgp.baseline.panel.years=c("2018", "2019", "2022"),
                 sgp.panel.years=c("2018", "2019", "2022"),
                 sgp.grade.sequences=list(c("1", "2", "5")),
                 sgp.baseline.grade.sequences=list(c("1", "2", "5")),
                 sgp.projection.sequence="READING_GRADE_5"),
     READING.2022 = list(
                 sgp.content.areas=c("READING", "READING", "READING"),
                 sgp.baseline.content.areas=c("READING", "READING", "READING"),
                 sgp.baseline.panel.years=c("2018", "2019", "2022"),
                 sgp.panel.years=c("2018", "2019", "2022"),
                 sgp.grade.sequences=list(c("2", "3", "6")),
                 sgp.baseline.grade.sequences=list(c("2", "3", "6")),
                 sgp.projection.sequence="READING_GRADE_6"),
     READING.2022 = list(
                 sgp.content.areas=c("READING", "READING", "READING"),
                 sgp.baseline.content.areas=c("READING", "READING", "READING"),
                 sgp.baseline.panel.years=c("2018", "2019", "2022"),
                 sgp.panel.years=c("2018", "2019", "2022"),
                 sgp.grade.sequences=list(c("3", "4", "7")),
                 sgp.baseline.grade.sequences=list(c("3", "4", "7")),
                 sgp.projection.sequence="READING_GRADE_7"),
     READING.2022 = list(
                 sgp.content.areas=c("READING", "READING", "READING"),
                 sgp.baseline.content.areas=c("READING", "READING", "READING"),
                 sgp.baseline.panel.years=c("2018", "2019", "2022"),
                 sgp.panel.years=c("2018", "2019", "2022"),
                 sgp.grade.sequences=list(c("4", "5", "8")),
                 sgp.baseline.grade.sequences=list(c("4", "5", "8")),
                 sgp.projection.sequence="READING_GRADE_8"),
     READING.2022 = list(
                 sgp.content.areas=c("READING", "READING", "READING"),
                 sgp.baseline.content.areas=c("READING", "READING", "READING"),
                 sgp.baseline.panel.years=c("2018", "2019", "2022"),
                 sgp.panel.years=c("2018", "2019", "2022"),
                 sgp.grade.sequences=list(c("5", "6", "9")),
                 sgp.baseline.grade.sequences=list(c("5", "6", "9")),
                 sgp.projection.sequence="READING_GRADE_9"),
     READING.2022 = list(
                 sgp.content.areas=c("READING", "READING", "READING"),
                 sgp.baseline.content.areas=c("READING", "READING", "READING"),
                 sgp.baseline.panel.years=c("2018", "2019", "2022"),
                 sgp.panel.years=c("2018", "2019", "2022"),
                 sgp.grade.sequences=list(c("6", "7", "10")),
                 sgp.baseline.grade.sequences=list(c("6", "7", "10")),
                 sgp.projection.sequence="READING_GRADE_10"),
     READING.2022 = list(
                 sgp.content.areas=c("READING", "READING", "READING"),
                 sgp.baseline.content.areas=c("READING", "READING", "READING"),
                 sgp.baseline.panel.years=c("2018", "2019", "2022"),
                 sgp.panel.years=c("2018", "2019", "2022"),
                 sgp.grade.sequences=list(c("7", "8", "11")),
                 sgp.baseline.grade.sequences=list(c("7", "8", "11")),
                 sgp.projection.sequence="READING_GRADE_11"),
     READING.2022 = list(
                 sgp.content.areas=c("READING", "READING", "READING"),
                 sgp.baseline.content.areas=c("READING", "READING", "READING"),
                 sgp.baseline.panel.years=c("2018", "2019", "2022"),
                 sgp.panel.years=c("2018", "2019", "2022"),
                 sgp.grade.sequences=list(c("8", "9", "12")),
                 sgp.baseline.grade.sequences=list(c("8", "9", "12")),
                 sgp.projection.sequence="READING_GRADE_12")
)
